### ISSUE TITLE
"WD14 moat tagger V2" not working?

### ISSUE THREAD

**Issue by Atoli** [picobyte/stable-diffusion-webui-wd14-tagger#19] opened 2023-07-18 21:30 UTC
When tried to use moat tagger i got the following error:

```
*** Error completing request
*** Arguments: (<PIL.Image.Image image mode=RGB size=1555x1920 at 0x1FF82014AF0>, 'WD14 moat tagger v2') {}
    Traceback (most recent call last):
      File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 261, in hf_raise_for_status
        response.raise_for_status()
      File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/SmilingWolf/wd-v1-4-moat-tagger-v2/resolve/main/C%3A%5CUsers%5CPC%5CDesktop%5Cstable-diffusion-webui%5Cmodels%5Cinterrogators%5Cmodels--SmilingWolf--wd-v1-4-moat-tagger-v2%5Csnapshots%5C8452cddf280b952281b6e102411c50e981cb2908%5Cmodel.onnx

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\Users\PC\Desktop\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\PC\Desktop\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\Users\PC\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py", line 80, in on_interrogate_image
        return interrogator.interrogate_image(image)
      File "C:\Users\PC\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 157, in interrogate_image
        data = ('', '', fi_key) + self.interrogate(image)
      File "C:\Users\PC\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 476, in interrogate
        self.load()
      File "C:\Users\PC\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 459, in load
        self.download()
      File "C:\Users\PC\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\interrogator.py", line 427, in download
        self.model_path = hf_hub_download(
      File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1195, in hf_hub_download
        metadata = get_hf_file_metadata(
      File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1541, in get_hf_file_metadata
        hf_raise_for_status(r)
      File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 271, in hf_raise_for_status
        raise EntryNotFoundError(message, response) from e
    huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64b703ec-5f4ac26f59b84daa707dcd7c;475d38c8-2ecd-48b7-a240-80cba4660f2a)

    Entry Not Found for url: https://huggingface.co/SmilingWolf/wd-v1-4-moat-tagger-v2/resolve/main/C%3A%5CUsers%5CPC%5CDesktop%5Cstable-diffusion-webui%5Cmodels%5Cinterrogators%5Cmodels--SmilingWolf--wd-v1-4-moat-tagger-v2%5Csnapshots%5C8452cddf280b952281b6e102411c50e981cb2908%5Cmodel.onnx.

---
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\PC\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [html, label, label, html]
Received outputs:
    [None, "", "<div class='error'>EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64b703ec-5f4ac26f59b84daa707dcd7c;475d38c8-2ecd-48b7-a240-80cba4660f2a)

Entry Not Found for url: https://huggingface.co/SmilingWolf/wd-v1-4-moat-tagger-v2/resolve/main/C%3A%5CUsers%5CPC%5CDesktop%5Cstable-diffusion-webui%5Cmodels%5Cinterrogators%5Cmodels--SmilingWolf--wd-v1-4-moat-tagger-v2%5Csnapshots%5C8452cddf280b952281b6e102411c50e981cb2908%5Cmodel.onnx.</div><div class='performance'><p class='time'>Time taken: <wbr>0.15s</p><p class='vram'>Torch active/reserved: 4095/4204 MiB, <wbr>Sys VRAM: 10179/12288 MiB (82.84%)</p></div>"]
```

All other models load normally.

**Comment by coder168** [comment] 2023-07-19 03:10
Same error here. 
But I found its little tricky, this error appear time to time. I am doing more tests to figure out how to replicate it reliably.

**Comment by coder168** [comment] 2023-07-19 04:50
After a quick check, what I found:
- this error happened to all Interrogators
- how to replicate this error:
  - after a few successful interrogate requests, click "Unload all interrogate models" button,
  - and then, request one more image, this error will appear on console, and tagger webui stop working until restart SD webui
- the possible cause as I found so far:
  - a very **questionable** code practice, give more than 1 purposes for a singe property. model_path in this case
  - in download functions of WaifuDiffusionInterrogator (line 427 of interrogator.py) & MLDanbooruInterrogator  (line 644 of interrogator.py), the value of model_path will be overwritten after successful huggingface model download, replaced with the local path of the model cached
  - however, the problem is if model is unloaded and we need run the request again, next time the download function will be executed with wrong model path value, eg, it was 'model.onnx' for WD14 moat tagger V2 at the first run, but will be replaced with cached local path after unload, so huggingface get an invalid request error back:
  - check the error message: "Entry Not Found for url: ...huggingface.co/SmilingWolf/wd-v1-4-moat-tagger-v2/resolve/main/**C%3A%5CUsers%5CPC%5CDesktop%5Cstable-diffusion-webui%5Cmodels%5Cinterrogators%5Cmodels--SmilingWolf--wd-v1-4-moat-tagger-v2%5Csnapshots%5C8452cddf280b952281b6e102411c50e981cb2908%5Cmodel.onnx**", that is the hashed local path of the cached model
  - please make necessary code change and fix the bug, thanks!

**Comment by picobyte** [comment] 2023-07-19 05:44
There were errors initially, with the model_path for some, so I kind of fixed it, but indeed it may be a hack, I will have a look.

**Comment by coder168** [comment] 2023-07-19 06:25
As what I guess:
- the current model retrieve mechanism relies on [hf_hub_download function](https://huggingface.co/docs/hub/models-downloading) from huggingface client lib,
- that hhd function is able to check the local cache model before start download the model from hf as long as the arguments are correct
- fact: our current impl can properly deal with cached model at first time, but it only failed at 2nd time retrieve after we unloaded the model from memory
- so in our current impl, by using the initial value of model_path as the 2nd argument passing to hhd function  the cached model  can be retrieved properly, but and then model_path get overwritten with the return value of hhd, which supposed to be the local path to the cached model. This cause hhd function request failed with overwritten value, since it will use 2nd argument to locate the file requested.

I wish this is helpful. Cheers.

**Comment by picobyte** [comment] 2023-07-19 06:29
yes, I came to something similar, make one model_path a local_path, namely the one assigned in `refresh_interrogators()`, and only for WaifuDiffusionInterrogator, but I think there is one more change necessary.

**Comment by coder168** [comment] 2023-07-19 06:36
I did test with ML-Danbooru Caformer dec-5-97527, same error happened too. So at least MLDanbooruInterrogator should be fixed as well.

**Comment by picobyte** [comment] 2023-07-19 07:06
so how about now?

**Comment by coder168** [comment] 2023-07-19 08:26
WaifuDiffusionInterrogator related interrogators get fixed, but MLDanbooruInterrogator related interrogators (ML-Danbooru Caformer dec-5-97527 & ML-Danbooru TResNet-D 6-30000) still has the same errors as before.

**Comment by picobyte** [comment] 2023-07-19 08:53
thanks, it seems fixed now also for ML Danbooru

**Comment by coder168** [comment] 2023-07-19 09:08
Yes, I have finished some tests and my testing results show all interrogators for both MLDanbooruInterrogator & WaifuDiffusionInterrogator works fine after unload. 

**Thanks for your excellent work!**

**Comment by picobyte** [comment] 2023-07-19 09:43
Thank you too, for the clear reporting.

**Closed by picobyte** 2023-07-19 09:43 UTC
