### ISSUE TITLE
tagger stop work on my mac

### ISSUE THREAD

**Issue by olymax** [picobyte/stable-diffusion-webui-wd14-tagger#40] opened 2023-08-05 14:22 UTC
After a few days of happily using the tagger, it suddenly stopped working.
everytime I start webui.sh.
always got a message like this :
2023-08-05 22:17:39,159 - ControlNet - INFO - ControlNet v1.1.234
*** Error loading script: tagger.py
    Traceback (most recent call last):
      File "/Users/mandoli/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/mandoli/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/mandoli/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/scripts/tagger.py", line 6, in <module>
        from tagger.ui import on_ui_tabs  # pylint: disable=import-error
      File "/Users/mandoli/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/tagger/ui.py", line 7, in <module>
        from tensorflow import __version__ as tf_version
    ModuleNotFoundError: No module named 'tensorflow'

or

*** Error running install.py for extension /Users/mandoli/SDWEBUI/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger.
*** Command: "/Users/mandoli/SDWEBUI/stable-diffusion-webui/venv/bin/python3.10" "/Users/mandoli/SDWEBUI/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/install.py"
*** Error code: 1
*** stdout: loading WD14-tagger reqs from /Users/mandoli/SDWEBUI/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/requirements.txt
*** Checking WD14-tagger requirements.
*** 
*** stderr: Traceback (most recent call last):
***   File "/Users/mandoli/SDWEBUI/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/install.py", line 11, in <module>
***     run(f'"{sys.executable}" -m pip install -q -r "{req_file}"',
***   File "/Users/mandoli/SDWEBUI/stable-diffusion-webui/modules/launch_utils.py", line 113, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install WD14-tagger requirements..
*** Command: "/Users/mandoli/SDWEBUI/stable-diffusion-webui/venv/bin/python3.10" -m pip install -q -r "/Users/mandoli/SDWEBUI/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/requirements.txt"
*** Error code: 1
*** stderr: ERROR: Could not find a version that satisfies the requirement tensorflow_io (from versions: none)
*** ERROR: No matching distribution found for tensorflow_io
*** 

it's look like tagger cann't connect with onnxruntime-silicon, I guess.

**Comment by picobyte** [comment] 2023-08-05 14:35
duplicate of #36

**Comment by picobyte** [comment] 2023-08-05 14:36
duplicate of #36

**Closed by picobyte** 2023-08-05 14:36 UTC
Labels: duplicate
